config/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from dashing.utils import router
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from jobboard.sitemaps import sitemaps

urlpatterns = [
    url('admin/', admin.site.urls),
    url('accounts/', include('allauth.urls')),
    url('techjobs/data/dashboard/', include(router.urls)),
    url('old_blog/', include('pinax.blog.urls', namespace='pinax_blog')),
    url('blog/', include(('content.urls', 'content'), namespace='blog')),
    url('ajax/images/', include('pinax.images.urls', namespace="pinax_images")),
    url('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('jobboard.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url('__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

content/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.blog_list, name='blog'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.blog, name='blog-post'),
    ]

jobboard/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from dal import autocomplete

from taggit.models import Tag
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('help/', views.help, name='help'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', TemplateView.as_view(template_name='privacy.html'), name='privacy'),
    path('prices/', views.prices, name='prices'),
    path('salary-check/', TemplateView.as_view(template_name='landing_salary_check.html'), name='landing-salary-check'),
    path('zaplata/', views.earning, name='landing-earning'),
    path('zaplata/success/', views.earning_success, name='earning-success'),
    path('talent/', views.landing_talent, name='landing-talent'),
    path('welcome/', login_required(TemplateView.as_view(template_name='welcome.html')), name='welcome'),
    path('api/jobs/', views.JobListAPI.as_view(), name='api-job-search'),
    path('api/skills/', views.SkillsAutocomplete.as_view(), name='autocomplete-skills'),
    path('epay/payment-notification/', views.payment_response),
    path('signup/user/', views.UserSignupView.as_view(), name='user-signup'),
    path('signup/applicant/', login_required(views.ApplicantSignupView.as_view()), name='register-applicant'),
    path('signup/company/', views.CompanySignupView.as_view(), name='register-company'),
    path('jobs/', views.jobs_search, name='jobs'),
    path('job/<int:id>/<slug:slug>/', views.jobpost, name='job'),
    path('job/<int:id>/', views.jobpost, name='job'),
    path('job/<int:id>/<slug:slug>/apply/', views.apply_direct, name='apply-direct'),
    path('companies/', views.company_list, name='company-list'),
    path('talent-search/', views.talent_search, name='talent-search'),
    path('accounts/<int:id>/', views.account_update, name='account-update'),
    path('accounts/registration/', views.registration, name='registration'),
    path('applicant/<int:id>/', views.applicant_home, name='applicant-home'),
    path('applicant/<int:id>/update/', views.applicant_update, name='applicant-update'),
    path('applicant/<int:id>/applications/', views.applicant_applications, name='applicant-applications'),
    path('applicant/<int:id>/salary-check/', views.salary_check, name='salary-check'),
    path('applicant/<int:id>/offers/', views.applicant_offers, name='applicant-offers'),
    path('offer/<int:pk>/', views.offer, name='offer'),
    path('offer/<int:pk>/remove/', views.remove_offer, name='offer-remove'),
    path('<slug:slug>/', views.company_home, name='company-home'),
    path('<slug:slug>/dashboard/', views.company_dashboard, name='company-dashboard'),
    path('<slug:slug>/credits/', views.buy_credits, name='buy-credits'),
    path('<slug:slug>/credits/pricing/', views.pricing, name='pricing'),
    path('<slug:slug>/credits/purchase/', views.new_purchase, name='new-purchase'),
    path('<slug:slug>/offers/', views.company_offers, name='company-offers'),
    path('<slug:slug>/make-offer/', views.make_offer, name='make-offer'),
    path('<slug:slug>/update/', views.company_update, name='company-update'),
    path('<slug:slug>/unsubscribe/<int:pk>', views.alerts_unsubscribe, name='alert-unsubscribe'),
    path('<slug:slug>/job/new/', views.jobpost_new, name='new-job'),
    path('<slug:slug>/job/<int:id>/repost/', views.jobpost_repost, name='jobpost-repost'),
    path('<slug:slug>/job/<int:id>/', views.company_jobpost, name='company-jobpost'),
    path('<slug:slug>/job/<int:id>/update/', views.jobpost_update, name='jobpost-update'),
    path('<slug:slug>/job/<int:id>/boost/', views.jobpost_boost, name='jobpost-boost'),
    path('<slug:slug>/job/<int:id>/application/<int:pk>/update/', views.application_update, name='application-update'),
    ]

jobboard/views.py
import datetime
import decimal
import hmac
import base64
import json
from hashlib import sha1

from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View,TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.db import transaction
from django.db.models import Q
from django.core.mail import send_mail, send_mass_mail, EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse, HttpResponseBadRequest
from django.core import serializers
from django.core.exceptions import ImproperlyConfigured
from django.utils import six
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.db.models import Avg
from django.utils.timezone import now
from django.http import HttpResponseRedirect

from allauth.account.views import SignupView
from rest_framework import generics
from dal import autocomplete
from taggit.models import Tag
#from pinax.blog.models import Post
from .models import Applicant, Company, JobPost, Application, Subscriber, Purchase, Salary, Offer
from content.models import BlogPost
from .forms import CompanySignupForm, CompanyUpdateForm, ApplicantSignupForm, ApplicantUpdateForm, NewJobPostForm, JobPostUpdateForm, UserUpdateForm, CompanySubscribeForm, JobPostFilterForm, PricingForm, EditApplicationForm, DirectApplicantForm, LeadForm, UserSignupForm, ApplicantSearchForm, OfferForm, SalarySearchForm
from jobboard.tasks import save_query_task
from .filters import CompanyFilter, JobPostFilter
from .serializers import CompanySerializer, JobPostSerializer, ApplicationSerializer
from .utils import calculate_price

###########################
# Main Views
###########################
def home(request):
    if request.GET.get('q') or request.GET.get('q') == '':
        search = request.GET.get('q')
        return redirect('/jobs/?{}={}'.format('q', search))

    try:
        recent_blogs = None #BlogPost.objects.order_by("-timestamp")[:3]
    except IndexError:
        recent_blogs = None

    context = {'page_title': 'Tech Hire | The Best Technical Jobs and Candidates in One Place', 'description': 'Search the top technical jobs in Bulgaria and discover the next great opportunity. Apply to roles at the best technology companies and startups with one click.', 'keywords': 'Tech, Jobs, Developer, Designer, Technology, Recruitment, Job',
        'recent_blogs': recent_blogs}

    if hasattr(request.user, 'applicant'):
        applicant = request.user.applicant
        if applicant.last_query:
            recommended_jobs = JobPost.objects.search(q=applicant.last_query).select_related()
            context['jobs'] = [job for job in recommended_jobs if job.min_salary and job.max_salary and job.currency][:4]
            return render(request, 'index.html', context)

    elif hasattr(request.user, 'company'):
        return render(request, 'index.html', context)

    recent_jobs = JobPost.objects.search().select_related()
    context['jobs'] = [job for job in recent_jobs if job.min_salary and job.max_salary and job.currency][:4]
    return render(request, 'index.html', context)


def jobs_search(request):
    jobs = JobPost.objects.search(**request.GET).select_related('company')

    search = request.GET.get('q')

    if hasattr(request.user, 'applicant') and search:
        applicant = request.user.applicant
        save_query_task.delay(applicant.id, search)

    experience = JobPost.EXPERIENCE
    job_type = JobPost.JOB_TYPE
    roles = JobPost.ROLES
    location = JobPost.LOCATION
    published = JobPost.PUBLISHED
    currency = JobPost.CURRENCIES
    form = JobPostFilterForm()
    description = 'Find software developer, designer, tech support and many other technical jobs at top startups and tech companies.'
    keywords = ' Jobs,'.join(role[0] for role in roles)
    context = {'jobs': jobs, 'search': search, 'exp': experience, 'job_type': job_type, 'roles': roles, 'location': location, 'published': published, 'currency':currency, 'slider': True, 'multiple': True, 'js': 'jobboard/js/functions.min.js', 'page_title': 'Jobs | Find your role at the best tech companies | Tech Hire', 'description': description, 'keywords': keywords}
    return render(request, 'jobs.html', context)


def jobpost(request, id, slug=None):
    jobpost = get_object_or_404(JobPost, pk=id)

    if jobpost.slug != slug:
        return redirect('job', id=id, slug=jobpost.slug)

    if jobpost.expired:
        return render(request, 'jobpost_expired.html', {'expired_job':jobpost.title})

    skills = jobpost.skills.names()
    keywords = ','.join(skills)
    title = '{} | Tech Hire'.format(jobpost)
    description = 'View job details and apply for {0} at {1} on Tech Hire https://techhire.bg{2}. Skills: {3} '.format(jobpost.title, jobpost.company,request.path, keywords)
    context = {'jobpost': jobpost, 'page_title': title, 'description': description, 'keywords': keywords}

    if request.method == 'POST':
        if request.user.is_authenticated:
            user = request.user
            if hasattr(user, 'applicant'):
                applicant = user.applicant
                if not applicant.resume:
                    context['error'] = 'Please add your CV to your account to be able to apply.'
                    context['js'] = 'jobboard/js/jobpage.min.js'
                    return render(request, 'jobpost.html', context)
                application, created = Application.objects.get_or_create(
                    applicant=applicant, job_post=jobpost, defaults={'resume':applicant.resume})
                context['application'] = application
                context['js'] = 'jobboard/js/jobpage.min.js'
                return render(request, 'jobpost.html', context)
            else:
                context['error'] = 'Please log in or register as an applicant to apply.'
                context['js'] = 'jobboard/js/jobpage.min.js'
                return render(request, 'jobpost.html', context)
        else:
            return redirect('apply-direct', id=id , slug=slug)

    return render(request, 'jobpost.html', context)


def apply_direct(request, id, slug=None):
    jobpost = get_object_or_404(JobPost, pk=id)
    form = DirectApplicantForm()
    context = {'form': form, 'js':'jobboard/js/profile1.min.js','multiple':True}
    if request.method == 'POST':
        form = DirectApplicantForm(request.POST, request.FILES)
        user = authenticate(email=form.data['email'], password=form.data['password1'], backend='django.contrib.auth.backends.ModelBackend')

        if user is not None:
            if hasattr(user, 'applicant'):
                application, created = Application.objects.get_or_create(applicant=user.applicant, job_post=jobpost, defaults={'resume':request.FILES.get('resume', user.applicant.resume)})
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                context.update({'applied': True, 'form': form, 'application': application, 'jobpost': jobpost})
                return render(request, 'apply_direct.html', context)
            else:
                context['errors'] = 'You cannot apply from a company account.'
                return render(request,'apply_direct.html', context)

        elif user is None and form.is_valid():
            form.cleaned_data['location'] = jobpost.location
            applicant = form.save(request)
            application, created = Application.objects.get_or_create(applicant=applicant, job_post=jobpost, defaults={'resume':applicant.resume})
            login(request, applicant.user, backend='django.contrib.auth.backends.ModelBackend')
            context.update({'applied': True, 'form': form, 'application': application, 'jobpost': jobpost})
            return render(request, 'apply_direct.html', context)

        else:
            if 'resume' in form.errors:
                context['errors'] = "CV must be a PDF or Word Document!"
            context['form'] = form
            return render(request, 'apply_direct.html', context)
    return render(request, 'apply_direct.html', context)

def earning(request):
    context = {'form': LeadForm, 'js':'jobboard/js/profile1.min.js', 'multiple':True}
    return render(request, 'landing_earning.html', context)


def landing_talent(request):
    context = {'form': UserSignupForm, 'js':'jobboard/js/profile1.min.js', 'multiple':True}
    return render(request, 'landing_signup.html', context)


@require_POST
def earning_success(request):
    form = LeadForm(request.POST)
    if form.is_valid():
        salaries = Salary.objects.filter(role=form.cleaned_data['role'], experience=form.cleaned_data['experience'], location='Sofia')
        context =  {'salaries': salaries, 'role': form.cleaned_data['role']}
        context['form'] = UserSignupForm()
        if not salaries:
            return render(request, 'landed.html', context)
        length = len(salaries)/2
        if length % 2 != 0:
            upper = sorted([s.salary for s in salaries])[-int(length+0.5):]
        else:
            upper = sorted([s.salary for s in salaries])[-int(length):]
        context['average'] = int(sum(upper)/len(upper))
        return render(request, 'landed.html', context)
    else:
        return redirect('landing-earning')


def company_list(request):
    f = CompanyFilter(request.GET, queryset=Company.objects.all().order_by('-last_job_post_date'))
    context = {'filter': f, 'page_title': 'Companies | Tech Hire', 'description': 'Browse top tech startups and companies and find your dream job.'}
    return render(request, 'company_list.html', context)


@login_required
def offer(request, pk):

jobboard/templates/pinax/blog/_pagination.html
{# Pagination for default django.core.paginator.Paginator #}
{# This template will work with CBV views with ``paginate_by`` specified. #}
{% load i18n %}

{% if is_paginated %}
<nav class="page-navigation" aria-label="page navigation">
    <ul>
        {% if page_obj.has_previous %}
            <li class="prev">
                <a href="?page={{ page_obj.previous_page_number|stringformat:"d" }}{{ getvars }}{{ hashtag }}">
                    <i class="fas fa-long-arrow-alt-left"></i>
                    {% trans "Previous" %}
                </a>
            </li>
        {% else %}
            <li class="prev disabled">
                <a>{% block pagination_previous_label %}<i class="fas fa-long-arrow-alt-left"></i> {% trans "Previous" %}{% endblock %}</a>
            </li>
        {% endif %}
        {% for page in paginator.page_range %}
            <li class="{% ifequal page page_obj.number %}active{% endifequal %}">
                <a href="?page={{ page|stringformat:"d" }}{{ getvars }}{{ hashtag }}">{{ page|stringformat:"d" }}</a>
            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="next">
                <a href="?page={{ page_obj.next_page_number|stringformat:"d" }}{{ getvars }}{{ hashtag }}">
                    {% trans "Next" %}
                    <i class="fas fa-long-arrow-alt-right"></i>
                </a>
            </li>
        {% else %}
            <li class="next disabled">
                <a>{% block pagination_next_label %}
                    {% trans "Next" %}
                    <i class="fas fa-long-arrow-alt-right"></i>
                    {% endblock %}
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

jobboard/templates/pinax/blog/blog_base.html
{% extends "jobboard/base.html" %}

{% load pinax_blog_tags %}

{% block body_class %}blog{% endblock %}

{% block body %}
    <div class="row blog-container">
        <div class="col-md-8 blog-content">
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4 sidebar">
                <h1>
                    {% if scoper_lookup %}
                        {% url "pinax_blog:blog" scoper_lookup as blog_url %}
                    {% else %}
                        {% url "pinax_blog:blog" as blog_url %}
                    {% endif %}
                    <a href="{{ blog_url }}">{{ SITE_NAME }}</a>
                </h1>
                <div class="profile-picture">
                    <img src="https://robohash.org/pinax" />
                </div>
                <p class="bio">
                    This is where you can list your bio, add links
                    etc., by editing the template found at:
                    <code>pinax/blog/blog_base.html</code>
                </p>
                <div class="feeds">
                    {% if scoper_lookup %}
                        {% url "pinax_blog:blog_feed" scoper_lookup "all" "atom" as feed_url %}
                    {% else %}
                        {% url "pinax_blog:blog_feed" "all" "atom" as feed_url %}
                    {% endif %}
                    <a href="{{ feed_url }}"><i class="fas fa-rss"></i> Atom Feed</a>
                </div>
                <div class="search">
                    {% if current_section == "all" %}
                        {% if scoper_lookup %}
                            {% url "pinax_blog:blog" scoper_lookup as search_url %}
                        {% else %}
                            {% url "pinax_blog:blog" as search_url %}
                        {% endif %}
                    {% else %}
                        {% if scoper_lookup %}
                            {% url "pinax_blog:blog_section" scoper_lookup current_section.slug as search_url %}
                        {% else %}
                            {% url "pinax_blog:blog_section" current_section.slug as search_url %}
                        {% endif %}
                    {% endif %}

                    <form class="form-search" action="{{ search_url }}">
                        <div class="search-input">
                            <div class="prepend-icon"><span><i class="fas fa-search"></i></span></div>
                            <input type="search" placeholder="Search..." name="q" value="{{ search_term|default:"" }}">
                        </div>
                    </form>
                </div>
                <nav class="sections-nav">
                    <div class="heading">Sections</div>
                    <a class="{% if current_section == "all" %}current-section{% endif %}" href="{{ blog_url }}">All</a>
                    {% blog_sections as sections %}
                    {% for section in sections %}
                        {% if scoper_lookup %}
                            {% url "pinax_blog:blog_section" scoper_lookup section.slug as section_url %}
                        {% else %}
                            {% url "pinax_blog:blog_section" section.slug as section_url %}
                        {% endif %}
                        <a class="{% if current_section == section %}current-section{% endif %}" href="{{ section_url }}">{{ section.name }}</a>
                    {% endfor %}
                </nav>

        </div>
    </div>
{% endblock %}

jobboard/templates/pinax/blog/blog_list.html
{% extends "pinax/blog/blog_base.html" %}

{% block head_title_base %}{{ SITE_NAME }}{% endblock %}


{% block content %}
    {% if post_list %}
        <div class="post-list">
            {% for post in post_list %}
                <div class="post card">
                    <div class="card-body">
                    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                    {% include "pinax/blog/dateline.html" %}
                    <div class="teaser">{{ post.teaser_html|safe }}</div>
                    <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% include "pinax/blog/_pagination.html" %}
    {% else %}
        <p class="alert alert-info lead">No blog posts have been published.</p>
    {% endif %}
{% endblock %}

jobboard/templates/pinax/blog/blog_post.html
{% extends "pinax/blog/blog_base.html" %}
{% load static %}
{% block body_class %}blog blog-post{% endblock %}

{% block title %}{{ post.title }} | Tech Hire{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <meta name="twitter:card" content="summary">
    {% comment %}
    <meta name="twitter:image" content="https://pbs.twimg.com/profile_images/62846141/pinaxproject_avatar.png">
    {% endcomment %}
    <meta property="og:title" content="{{ post.title }}">
    {% if post.description %}
        <meta name="description" content="{{ post.description }}">
        <meta property="og:description" content="{{ post.description }}">
    {% else %}
        <meta name="description" content="{{ post.teaser_html|striptags }}">
        <meta property="og:description" content="{{ post.teaser_html|striptags }}">
    {% endif %}
    {% if post.primary_image %}
        <meta property="og:image" content="http://{{ SITE_DOMAIN }}{{ post.primary_image.image_path.url }}">
    {% else %}
        {% comment %}
        <meta property="og:image" content="https://pbs.twimg.com/profile_images/62846141/pinaxproject_avatar.png">
        {% endcomment %}
    {% endif %}
    <meta property="og:url" content="http://{{ SITE_DOMAIN }}{{ post.get_absolute_url }}">
    <meta property="og:type" content="article">
    <link rel="stylesheet" href="https://emailoctopus.com/bundles/emailoctopuslist/css/formEmbed.css?1542118937">
{% endblock %}

{% block content %}
    <div class="post-detail card">
        <div class="post card-body">
            <h1>{{ post.title }}</h1>
            {% include "pinax/blog/dateline_stale.html" %}

            <div class="teaser">{{ post.teaser_html|safe }}</div>

            <div>{{ post.content_html|safe }}</div>

            <div class="twitter-button">
                <a href="https://twitter.com/share" class="twitter-share-button" data-via="">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
        </div>
    </div>

<div class="modal" id="subscribeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Абонирай се за Нови Постове</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post"
                  action="https://emailoctopus.com/lists/5c7b28fa-e7cb-11e8-a3c9-06b79b628af2/members/embedded/1.3/add"
                  class=""
                  data-sitekey="6LdYsmsUAAAAAPXVTt-ovRsPIJ_IVhvYBBhGvRV6"
                >
                    <div class="email-octopus-form-row">
                        <input type="hidden" name="successRedirectUrl" value="">
                        <input id="field_0" name="field_0" type="email" class="form-control" placeholder="Email">
                        <button type="submit" class="btn btn-action btn-landing">Subscribe</button>
                    </div>

                    <div class="email-octopus-form-row-hp d-none" aria-hidden="true">
                        <!-- Do not remove this field, otherwise you risk bot sign-ups -->
                        <input type="text" name="hp5c7b28fa-e7cb-11e8-a3c9-06b79b628af2"
                           tabindex="-1"
                           autocomplete="nope">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="{% static 'jobboard/js/blog.min.js' %}"></script>
<script src="https://emailoctopus.com/bundles/emailoctopuslist/js/1.3/formEmbed.js?1542118937"></script>
{% endblock %}