config/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from dashing.utils import router
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from jobboard.sitemaps import sitemaps

urlpatterns = [
    url('admin/', admin.site.urls),
    url('accounts/', include('allauth.urls')),
    url('techjobs/data/dashboard/', include(router.urls)),
    url('old_blog/', include('pinax.blog.urls', namespace='pinax_blog')),
    url('blog/', include(('content.urls', 'content'), namespace='blog')),
    url('ajax/images/', include('pinax.images.urls', namespace="pinax_images")),
    url('robots.txt/', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('jobboard.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url('__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

jobboard/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from dal import autocomplete

from taggit.models import Tag
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('help/', views.help, name='help'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', TemplateView.as_view(template_name='privacy.html'), name='privacy'),
    path('prices/', views.prices, name='prices'),
    path('salary-check/', TemplateView.as_view(template_name='landing_salary_check.html'), name='landing-salary-check'),
    path('zaplata/', views.earning, name='landing-earning'),
    path('zaplata/success/', views.earning_success, name='earning-success'),
    path('talent/', views.landing_talent, name='landing-talent'),
    path('welcome/', login_required(TemplateView.as_view(template_name='welcome.html')), name='welcome'),
    path('api/jobs/', views.JobListAPI.as_view(), name='api-job-search'),
    path('api/skills/', views.SkillsAutocomplete.as_view(), name='autocomplete-skills'),
    path('epay/payment-notification/', views.payment_response),
    path('signup/user/', views.UserSignupView.as_view(), name='user-signup'),
    path('signup/applicant/', login_required(views.ApplicantSignupView.as_view()), name='register-applicant'),
    path('signup/company/', views.CompanySignupView.as_view(), name='register-company'),
    path('jobs/', views.jobs_search, name='jobs'),
    path('job/<int:id>/<slug:slug>/', views.jobpost, name='job'),
    path('job/<int:id>/', views.jobpost, name='job'),
    path('job/<int:id>/<slug:slug>/apply/', views.apply_direct, name='apply-direct'),
    path('companies/', views.company_list, name='company-list'),
    path('talent-search/', views.talent_search, name='talent-search'),
    path('accounts/<int:id>/', views.account_update, name='account-update'),
    path('accounts/registration/', views.registration, name='registration'),
    path('applicant/<int:id>/', views.applicant_home, name='applicant-home'),
    path('applicant/<int:id>/update/', views.applicant_update, name='applicant-update'),
    path('applicant/<int:id>/applications/', views.applicant_applications, name='applicant-applications'),
    path('applicant/<int:id>/salary-check/', views.salary_check, name='salary-check'),
    path('applicant/<int:id>/offers/', views.applicant_offers, name='applicant-offers'),
    path('offer/<int:pk>/', views.offer, name='offer'),
    path('offer/<int:pk>/remove/', views.remove_offer, name='offer-remove'),
    path('<slug:slug>/', views.company_home, name='company-home'),
    path('<slug:slug>/dashboard/', views.company_dashboard, name='company-dashboard'),
    path('<slug:slug>/credits/', views.buy_credits, name='buy-credits'),
    path('<slug:slug>/credits/pricing/', views.pricing, name='pricing'),
    path('<slug:slug>/credits/purchase/', views.new_purchase, name='new-purchase'),
    path('<slug:slug>/offers/', views.company_offers, name='company-offers'),
    path('<slug:slug>/make-offer/', views.make_offer, name='make-offer'),
    path('<slug:slug>/update/', views.company_update, name='company-update'),
    path('<slug:slug>/unsubscribe/<int:pk>', views.alerts_unsubscribe, name='alert-unsubscribe'),
    path('<slug:slug>/job/new/', views.jobpost_new, name='new-job'),
    path('<slug:slug>/job/<int:id>/repost/', views.jobpost_repost, name='jobpost-repost'),
    path('<slug:slug>/job/<int:id>/', views.company_jobpost, name='company-jobpost'),
    path('<slug:slug>/job/<int:id>/update/', views.jobpost_update, name='jobpost-update'),
    path('<slug:slug>/job/<int:id>/boost/', views.jobpost_boost, name='jobpost-boost'),
    path('<slug:slug>/job/<int:id>/application/<int:pk>/update/', views.application_update, name='application-update'),
    ]

jobboard/models.py
import datetime
import string
import base64

from django.db import models, transaction
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField, JSONField
from django.utils.translation import gettext as _
from django.db.models import Q
from django.core.mail import send_mail, send_mass_mail, EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.crypto import get_random_string
from django.db.models.signals import pre_save
from django.urls import reverse
from django.conf import settings
from django.core.validators import FileExtensionValidator

from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
# Create your models here.

DEV = (
    ('Software Developer', _('Software Developer')),
    ('Front-End Developer', _('Front-End Developer')),
    ('Back-End Developer', _('Back-End Developer')),
    ('Full-Stack Developer', _('Full-Stack Developer')),
    ('DevOps Developer', _('DevOps Developer')),
    ('Mobile Developer', _('Mobile Developer')),
    ('Database Developer', _('Database Developer')),
    ('QA Engineer', _('QA Engineer')),
    ('Team Lead', _('Team Lead')),
    ('CTO', 'CTO'),
    )

DESIGN = (
    ('Web Designer', _('Web Designer')),
    ('Graphic Designer', _('Graphic Designer')),
    ('UI/UX Designer', _('UI/UX Designer')),
    ('UX Researcher', _('UX Researcher')),
    )

SUPPORT = (
    ('Technical Support', _('Technical Support')),
    ('Customer Support', _('Customer Support')),
    ('Customer Service', _('Customer Service')),
    )

DATA = (
    ('Data Analyst', _('Data Analyst')),
    ('Data Scientist', _('Data Scientist')),
    )

PRODUCT = (
    ('Project Manager', _('Project Manager')),
    ('Product Manager', _('Product Manager')),
    ('Product Owner', _('Product Owner')),
    ('Scrum Master', _('Scrum Master')),
)

ADMIN = (
    ('System Administrator', _('System Administrator')),
    ('Database Administrator', _('Database Administrator')),
    ('Network Administrator', _('Network Administrator')),
    )

ENG = (
    ('Hardware Engineer', _('Hardware Engineer')),
    ('Network Engineer', _('Network Engineer')),
    )

MARKETING = (
    ('Content Marketer', _('Content Marketer')),
    ('Digital Marketer', _('Digital Marketer')),
    ('Social Media Manager', _('Social Media Manager')),
    ('Marketing Manager', _('Marketing Manager')),
    )

BUSINESS = (
    ('Business Analyst', _('Business Analyst')),
    ('Account Manager', _('Account Manager')),
    ('Sales Representative', _('Sales Representative')),
    ('Human Resources', _('Human Resources')),
    ('Consultant', _('Consultant')),
    ('Other', _('Other')),
    )

ROLES = DEV + DESIGN + SUPPORT + DATA + PRODUCT + ADMIN + ENG + MARKETING + BUSINESS

CURRENCIES = (
    ('BGN', 'BGN'),
    ('EUR', 'EUR'),
    ('USD', 'USD'),
    )

EXPERIENCE = (
    ('Intern', _('Intern')),
    ('Graduate', _('Graduate')),
    ('Junior', _('Junior')),
    ('Mid', _('Mid-level')),
    ('Senior', _('Senior')),
    ('Lead', _('Lead')),
    ('Manager', _('Manager')),
    )

JOB_TYPE = (
    ('Full-time', _('Full-time')),
    ('Contract', _('Contract')),
    ('Part-time', _('Part-time')),
    ('Internship', _('Internship')),
    ('Freelance', _('Freelance')),
    )

LOCATION = (
    ('Sofia', _('Sofia')),
    ('Plovdiv', _('Plovdiv')),
    ('Varna', _('Varna')),
    ('Burgas', _('Burgas')),
    ('Ruse', _('Ruse')),
    ('Stara Zagora', _('Stara Zagora')),
    ('Remote', _('Remote')),
    ('Work Abroad', _('Work Abroad')),
    ('Other', _('Other')),
    )

PUBLISHED = (
    ('Today', _('Today')),
    ('1 Day ago', _('1 Day ago')),
    ('3 Days ago', _('3 Days ago')),
    ('7 Days ago', _('7 Days ago')),
    ('15 Days ago', _('15 Days ago')),
    )


COMPANY_SIZE = (
    ('1-10', '1-10'),
    ('11-50', '11-50'),
    ('51-200', '51-200'),
    ('201-500', '201-500'),
    ('501-1000', '501-1000'),
    ('1001-5000', '1001-5000'),
    ('5000+', '5000+'),
    )

EDUCATION = (
    ('High School', _('High School')),
    ('Bachelors', _('Bachelors')),
    ("Master's", _('Masters')),
    ('PhD', _('PhD')),
    )

YEARS = (
    ('0-1', '0-1 Years'),
    ('1-3', '1-3 Years'),
    ('4-6', '4-6 Years'),
    ('7-10', '7-10 Years'),
    ('10+', '10+ Years'),
)


class Applicant(models.Model):
    ROLES = ROLES
    user       = models.OneToOneField(User, on_delete=models.CASCADE, related_name='applicant')
    full_name  = models.CharField(max_length=100)
    phone      = models.CharField(max_length=50, blank=True)
    location   = models.CharField(max_length=50, default='Sofia', choices=LOCATION)
    resume     = models.FileField(upload_to='', validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], blank=True)
    looking    = models.BooleanField(default=True)
    role       = models.CharField(max_length=50, choices=ROLES, null=True)
    roles      = ArrayField(models.CharField(max_length=50, choices=ROLES, blank=True), null=True, blank=True)
    degree     = models.CharField(max_length=50, blank=True, choices=EDUCATION)
    languages  = ArrayField(models.CharField(max_length=30, blank=True), null=True, blank=True)
    linkedin   = models.URLField(max_length=250, blank=True)
    github     = models.URLField(max_length=250, blank=True)
    behance    = models.URLField(max_length=250, blank=True)
    website    = models.URLField(max_length=250, blank=True)
    last_query = models.TextField(null=True, editable=False)
    experience = models.CharField(max_length=50, choices=YEARS)
    job_type   = models.CharField(max_length=50, choices=JOB_TYPE, blank=True)
    current_salary        = models.PositiveIntegerField(blank=True, null=True)
    desired_salary        = models.PositiveIntegerField(blank=True, null=True)
    marketing_consent     = models.BooleanField(default=False)
    last_query_date       = models.DateField(null=True, blank=True)
    last_application_date = models.DateField(null=True, blank=True)
    resume_upload_date    = models.DateField(null=True, blank=True)

    skills = TaggableManager(verbose_name='Skills')

    def __str__(self):
        return '{}'.format(self.full_name)

    def model_name(self):
        return self._meta.verbose_name

    def save(self, *args, **kwargs):
        created = self.pk is None
        super().save(*args, **kwargs)
        if created:
            self.onboarding_email()

    def onboarding_email(self):
        subject = 'Welcome to Tech Hire'
        link = 'applicant/{}/'.format(self.pk)
        context = {'name':self.full_name.split()[0], 'link': link}
        text_content = render_to_string('email/user_onboarding.txt', context)
        html_content = render_to_string('email/user_onboarding.html', context)
        mail = self.user.email
        msg = EmailMultiAlternatives(subject, text_content, 'mail@techhire.bg', [mail])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()
        return


class Company(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE, related_name='company')
    name        = models.CharField('Company Name', max_length=50, unique=True)
    slug        = models.SlugField(editable=False, unique=True, max_length=255)
    phone       = models.CharField('Company Phone', max_length=50)
    website     = models.URLField(max_length=250, blank=True)
    description = RichTextField()
    logo        = models.ImageField(null=True, blank=True)
    background  = models.ImageField(null=True, blank=True)
    city        = models.CharField(max_length=50, blank=True)
    address     = models.CharField(max_length=250, blank=True)
    team_size   = models.CharField(max_length=20, choices=COMPANY_SIZE, blank=True)
    benefits    = ArrayField(models.CharField(max_length=50), null=True, blank=True)
    credits     = models.DecimalField(max_digits=5, decimal_places=1, default=1, blank=True)
    recruiter   = models.BooleanField(default=False)
    marketing_consent     = models.BooleanField(default=True)
    contact_email         = models.EmailField(null=True, blank=True)
    notification_email    = models.EmailField(null=True, blank=True)
    recruiter_expiry_date = models.DateField(null=True, blank=True)
    last_job_post_date    = models.DateField(null=True, blank=True)
    modified_date         = models.DateField(auto_now=True)

    skills = TaggableManager(verbose_name='Skills', blank=True)

    def __str__(self):
        return '{}'.format(self.name)

    def get_absolute_url(self):
        return reverse('company-home', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        created = self.pk is None
        super().save(*args, **kwargs)
        if created:
            self.onboarding_email()

    def onboarding_email(self):
        subject = 'Welcome to Tech Hire'
        link = '{}/job/new/'.format(self.slug)
        context = {'company':self, 'link': link}
        text_content = render_to_string('email/company_onboarding.txt', context)
        html_content = render_to_string('email/company_onboarding.html', context)
        mail = self.user.email
        msg = EmailMultiAlternatives(subject, text_content, 'mail@techhire.bg', [mail])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()
        return


class JobPostManager(models.Manager):
    def search(self, *args, **kwargs):
        qs = self.get_queryset()
        args = []
        params = {'expired': 'False'}
        if 'q' in kwargs:
            q = kwargs['q'][0]
            table = str.maketrans({key: None for key in string.punctuation})
            q = q.translate(table)
            args.append(Q(title__icontains=q) | Q(skills__name__in=q.split()))
        if 'company' in kwargs:
            params['company__name__icontains'] = kwargs['company'][0]
        if 'job_type' in kwargs:
            filters = None
            for job_type in kwargs['job_type'][0].split(','):

jobboard/templates/jobboard/account_update.html
{% extends 'base.html' %}

{% block content %}

<h3 class="page-title">Account Details</h3>

<h3>{{message}}</h3>
{% load crispy_forms_tags %}
<div class="card small-card">
<div class="card-body">
{% crispy form %}
</div>
</div>
{% endblock %}

jobboard/templates/jobboard/company_jobpost.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
<div class="col-sm-6">
<div class="card">
 <div class="card-body">
    {{jobpost.title| title}}
    <a href="{% url 'jobpost-update' slug jobpost.id %}"><p>Edit Job</p></a>
    <div class="row">
        <div class="col-6 col-lg-3 text-center">
            <span>Applicants</span> <div>{{applications|length}}</div></div>
        <div class="col-6 col-lg-3 text-center">
            <div>Interviews</div> <div>{{interviews|length}}</div></div>
        <div class="col-6 col-lg-3 text-center">
            <div>Offer</div> <div>{{offers|length}}</div></div>
        <div class="col-6 col-lg-3 text-center">
            <div>Hired</div><div>{{hired|length}}</div></div>
    </div>
 </div>
</div>
</div>
<div class="col-sm-6">
<div class="search-box">
    <div class="search-query">
        <i class="fa fa-search fa-lg" aria-hidden="true"></i>
        <input class="form-control jobsSearch" placeholder="Search &amp; Filter Applicants" id="search-field">
    </div>
    <div class="row">
    <div class="col-6 text-center">
    <form method="GET" id="rejectedForm">
        <input type="hidden" name="rejected" value="true">
    </form>
    <button type="submit" form="rejectedForm" class="btn btn-outline-primary">Show Rejected</button>
    </div>
    <div class="col-6 text-center">
    <form method="GET" id="interviewForm">
        <input type="hidden" name="status" value="Interview">
    </form>
    <button type="submit" form="interviewForm" class="btn btn-outline-primary">Show Interviews</button>
    </div>
</div>
</form>
</div>

</div>
</div>

<div class="limiter" id="appList">
<div class="container-table100">
<div class="wrap-table100">
<table class="app-table">
    <thead>
    <tr class="row app-row header">
        <th class="cell sort" data-sort="name">Name</th>
        <th class="cell">Email</th>
        <th class="cell d-none d-md-block mt11">Phone</th>
        <th class="cell">CV</th>
        <th class="cell sort" data-sort="application_date" style="white-space: pre-line;">Application
        Date</th>
        <th class="cell sort" data-sort="status">Status</th>
        <th class="cell sort d-none d-lg-block mt11" data-sort="rating">Rating</th>
        <th class="cell sort hidden" data-sort="comment">Comment</th>
        <th class="cell sort" style="white-space: pre-line;" data-sort="interview_date">Interview
        Date</th>
        <th class="cell">Actions</th>
    </tr>
    </thead>
    <tbody class="list">
    {% for app in applications %}
    <tr class="row app-row" id="application{{app.id}}">
        <td class="cell name" data-title="Name">{{app.applicant.user.first_name|title}} {{app.applicant.user.last_name|title}}</td>
        <td class="cell" data-title="Email">{{app.applicant.user.email}}</td>
        <td class="cell d-none d-md-block mt11" data-title="Phone">{{app.applicant.phone}}</td>
        <td class="cell" data-title="CV"><a href="{{app.resume.url}}" Download> Download CV</a></td>
        <td class="cell application_date" data-title="Application Date">{{app.created_date|date:"d.m.Y" }}</td>
        <td class="cell status" data-title="Status">{{app.status}}</td>
        <td class="cell rating d-none d-lg-block" data-title="Rating" data-value="{{app.aplicant_rating}}">{{app.get_applicant_rating_display}}</td>
        <td class="cell hidden" data-title="Comment">{{app.comment}}</td>
        <td class="cell interview_date" data-title="Interview Date">{{app.interview_date|date:"d.m.Y"}}</td>
        <td class="cell" data-title="Actions"><button type="button" data-toggle="modal" data-target="#applicantModal" data-app-id="{{app.id}}" data-cv="{{app.applicant.resume.url}}" class="btn btn-primary open-app">Open</button></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div>
</div>
</div>

<div class="modal fade" id="applicantModal" tabindex="-1" role="dialog" aria-labelledby="applicantModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="applicantModalLabel">Application</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="col-sm-6">
                <label class="form-control-label" for="id_name">Name</label>
                <p id="id_name"></p>
            </div>
            <div class="col-sm-6">
                <label class="form-control-label" for="id_email">Email</label>
                <p id="id_email"></p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label class="form-control-label" for="id_phone">Phone</label>
                <p id="id_phone"></p>
            </div>
            <div class="col-sm-4">
                <label class="form-control-label" for="id_cv">CV</label>
                <p><a href="" id="id_cv" Download> Download CV</a></p>
            </div>
            <div class="col-sm-4">
                <label class="form-control-label" for="id_application_date">Application Date</label>
                <p id="id_application_date"></p>
            </div>
        </div>
        <hr>
        {% load crispy_forms_tags %}
        {% crispy form %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" id="saveApplication" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

jobboard/templates/jobboard/company_signup.html
{% extends 'base.html' %}

{% block content %}

<h3 class="page-title">Company Registration</h3>

<div class="card small-card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
            <p class="underline">Step 1</p>
            <p>Create Account</p>
            </div>
            <div class="col-sm-6">
            <p>Step 2</p>
            <p>Complete Company Profile</p>
            </div>
        </div>
    </div>
</div>

{% load crispy_forms_tags %}
<div class="card">
    <div class="card-body">
        {% crispy form %}
    </div>
</div>
{% endblock %}

jobboard/templates/jobboard/company_update.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<h3 class="page-title">Update Company</h3>

<div class="card">
    <div class="card-body">
     {% crispy form %}
    </div>
</div>
{% endblock %}

jobboard/templates/jobboard/jobpost.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{page_title}} {%endblock%}
{% block content %}
{% if jobpost.company.background %}
<div class="company-background" style="background-image: url({{jobpost.company.background.url}});">
</div>
{% else %}
<div class="company-background">
</div>
{% endif %}
<div class="card jobpage-card">
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-3 mx-auto text-center">
                    <div>
                        {% if jobpost.company.logo %}
                        <div class="company-logo-wrapper">
                            <img src="{{jobpost.company.logo.url}}" alt="{{company.name |title}} logo">
                        </div>
                            {% else %}
                            <div class="company-logo-wrapper">
                            </div>
                            {% endif %}
                            <h5 class="company-page-title"><a href="{% url 'company-home' jobpost.company.slug %}">{{jobpost.company.name|title}}</a></h5>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <h1 class="jobpage-title">{{jobpost.title}}</h1>
                        <div class="row">
                            <div class="col-sm-6">
                                {% if jobpost.experience %}
                                <div class="job-info-label">Experience</div>
                                <div>{{jobpost.get_experience_display}}</div>
                                {% endif %}
                                {% if jobpost.job_type %}
                                <div class="job-info-label">Job Type</div>
                                <div>{{jobpost.job_type}}</div>
                                {% endif %}
                            </div>
                            <div class="col-sm-6">
                                {% if jobpost.role %}
                                <div class="job-info-label">Role</div>
                                <div>{{jobpost.role}}</div>
                                {% endif %}
                                {% if jobpost.location %}
                                <div class="job-info-label">Location</div>
                                <div>{{jobpost.location}}</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 text-center mt-3">
                        {% if jobpost.min_salary or jobpost.max_salary %}
                        <div class="listing-salary">
                            <span class="">{{jobpost.min_salary|default_if_none:'&nbsp;'}} - {{jobpost.max_salary|default_if_none:'&nbsp;'}}
                {{jobpost.currency|default_if_none:'&nbsp;'}}</span>
                        </div>
                        {% endif %}
                        <button type="submit" class="btn btn-action btn-apply d-none d-sm-block" name="apply" value="Apply">Apply</button>
                    </div>
                </div>
                {% if jobpost.skills %}
                    <hr>
                    <div class="row">
                        <div class="col-12">
                            <div class="job-info-label">Skills</div>
                            <div>
                                {% for skill in jobpost.skills.names %}
                                <div class="tag">{{skill}}</div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endif %}
                <hr>
                <div class="row">
                    <div class="col-12">
                        <div class="job-info-label">Job Description</div>
                        <div>
                            <p>{{jobpost.description|safe}}</p>
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-action btn-apply" name="apply" value="Apply">Apply</button>
                </div>
        </form>
    </div>
    <div class="card-footer">
        Published {{jobpost.publish_date|date}}
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6 job-info-label">
                Share on
                <a href="https://www.facebook.com/sharer/sharer.php?u=https://techhire.bg{{ request.path }}" target="_blank"><img src="{% static 'jobboard/images/flogo.png' %}" alt="Facebook Share" class="share-icon"/></a>
                <a href="http://twitter.com/share?text={{description}}&url=https://techhire.bg{{ request.path }}">
                <img src="{% static 'jobboard/images/Twitter_Logo.png' %}" class="share-icon" alt="Twitter Logo">
                </a>
                <a href="https://www.linkedin.com/shareArticle?mini=true&url=https://techhire.bg{{ request.path }}&title={{jobpost.title}}&summary={{description}}">
                <img src="{% static 'jobboard/images/Inlogo.png' %}" alt="LinkedIn Share" class="share-icon"></a>
            </div>
            <div class="col-sm-6 job-info-label">
                Email job <a href="mailto:?body={{description}}&subject={{jobpost.title}}"> <img src="{% static 'jobboard/images/gmail.png' %}" alt="Email Job" class="share-icon"></a>
            </div>
        </div>
    </div>
</div>

{% if application %}
<div class="modal fade" id="applicationResponseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Application Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                You have applied for {{jobpost.title}} at {{jobpost.company}} on {{application.created_date}}!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% if error %}
<div class="modal fade" id="errorResponseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Error</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{error}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

jobboard/templates/jobboard/profile.html
{% extends 'base.html' %}

{% block content %}

{{ user.email}}
{{user.last_name}}

{{ applicant}}
{% endblock %}